"""create product family and attribute definitions

Revision ID: 0762826c32b2
Revises: 
Create Date: 2026-04-12 12:04:59.723969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0762826c32b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_families_code'), 'product_families', ['code'], unique=True)
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attribute_type', sa.Enum('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'ENUM', name='attribute_type_enum'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('min_int', sa.Integer(), nullable=True),
    sa.Column('max_int', sa.Integer(), nullable=True),
    sa.Column('min_decimal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_decimal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_family_id', 'code', name='uq_attribute_definition_family_code')
    )
    op.create_index(op.f('ix_attribute_definitions_product_family_id'), 'attribute_definitions', ['product_family_id'], unique=False)
    op.create_table('attribute_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_definition_id'], ['attribute_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_definition_id', 'value', name='uq_attribute_option_value')
    )
    op.create_index(op.f('ix_attribute_options_attribute_definition_id'), 'attribute_options', ['attribute_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribute_options_attribute_definition_id'), table_name='attribute_options')
    op.drop_table('attribute_options')
    op.drop_index(op.f('ix_attribute_definitions_product_family_id'), table_name='attribute_definitions')
    op.drop_table('attribute_definitions')
    op.drop_index(op.f('ix_product_families_code'), table_name='product_families')
    op.drop_table('product_families')
    # ### end Alembic commands ###
