"""add product pricing rules

Revision ID: 4ceac1e0dcd9
Revises: ddcc497f7e6a
Create Date: 2026-04-12 15:39:13.042820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceac1e0dcd9'
down_revision: Union[str, Sequence[str], None] = 'ddcc497f7e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pricing_rule_type', sa.Enum('BASE_PRICE', 'FIXED_SURCHARGE', 'PERCENTAGE_SURCHARGE', name='pricing_rule_type_enum'), nullable=False),
    sa.Column('if_attribute_code', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.Enum('EQ', 'NEQ', 'GT', 'GTE', 'LT', 'LTE', 'IN', name='pricing_rule_operator_enum'), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_pricing_rules_product_family_id'), 'product_pricing_rules', ['product_family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_pricing_rules_product_family_id'), table_name='product_pricing_rules')
    op.drop_table('product_pricing_rules')
    # ### end Alembic commands ###
