"""add product quotes

Revision ID: 7bd6e0ccd34b
Revises: 4ceac1e0dcd9
Create Date: 2026-04-12 16:32:22.222132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd6e0ccd34b'
down_revision: Union[str, Sequence[str], None] = '4ceac1e0dcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_configuration_id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='quote_status_enum'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surcharge_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_configuration_id'], ['product_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_quotes_product_configuration_id'), 'product_quotes', ['product_configuration_id'], unique=False)
    op.create_index(op.f('ix_product_quotes_quote_number'), 'product_quotes', ['quote_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_quotes_quote_number'), table_name='product_quotes')
    op.drop_index(op.f('ix_product_quotes_product_configuration_id'), table_name='product_quotes')
    op.drop_table('product_quotes')
    # ### end Alembic commands ###
