"""add product configurations and attribute values

Revision ID: b52eb079b65b
Revises: 0762826c32b2
Create Date: 2026-04-12 13:43:40.945739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52eb079b65b'
down_revision: Union[str, Sequence[str], None] = '0762826c32b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_configurations_product_family_id'), 'product_configurations', ['product_family_id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('attribute_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.String(length=255), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_decimal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_definition_id'], ['attribute_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configuration_id'], ['product_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_id', 'attribute_definition_id', name='uq_attribute_value_configuration_attribute')
    )
    op.create_index(op.f('ix_attribute_values_attribute_definition_id'), 'attribute_values', ['attribute_definition_id'], unique=False)
    op.create_index(op.f('ix_attribute_values_configuration_id'), 'attribute_values', ['configuration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribute_values_configuration_id'), table_name='attribute_values')
    op.drop_index(op.f('ix_attribute_values_attribute_definition_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_product_configurations_product_family_id'), table_name='product_configurations')
    op.drop_table('product_configurations')
    # ### end Alembic commands ###
