"""add product rules

Revision ID: ddcc497f7e6a
Revises: b52eb079b65b
Create Date: 2026-04-12 15:27:38.262336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcc497f7e6a'
down_revision: Union[str, Sequence[str], None] = 'b52eb079b65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('REQUIRES_ATTRIBUTE', 'FORBIDS_ATTRIBUTE', 'RESTRICTS_VALUE', name='rule_type_enum'), nullable=False),
    sa.Column('if_attribute_code', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.Enum('EQ', 'NEQ', 'GT', 'GTE', 'LT', 'LTE', 'IN', name='rule_operator_enum'), nullable=False),
    sa.Column('expected_value', sa.String(length=255), nullable=False),
    sa.Column('target_attribute_code', sa.String(length=100), nullable=False),
    sa.Column('allowed_values', sa.Text(), nullable=True, comment='Comma-separated values used by restricts_value rules.'),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_family_id'], ['product_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_rules_product_family_id'), 'product_rules', ['product_family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_rules_product_family_id'), table_name='product_rules')
    op.drop_table('product_rules')
    # ### end Alembic commands ###
